// src/constants/discData.ts

// — Brands —
// Not exhaustive, but covers many major disc manufacturers.  
// You can add more over time (e.g. specialty, boutique, secondary brands).
export const DiscBrands = [
  "ABC",
  "Above Ground Level",
  "Axiom",
  "Clash Discs",
  "Climo Disc Golf",
  "Daredevil",
  "DGA",
  "Discmania",
  "Discraft",
  "Dynamic Discs",
  "Element Discs",
  "Elevation",
  "EV-7",
  "Full Turn",
  'Galaxy Disc Golf',
  "Gateway",
  "Hyzerbomb",
  "Infinite Discs",
  "Innova",
  "Kastaplast",
  "Latitude 64",
  "Legacy",
  "Lone Star Discs",
  "Millenium",
  "Mint Discs",
  "MVP",
  "Plastic Addicts",
  "Prodigy",
  "Prodiscus",
  "Reptilian Disc Golf",
  "RPM",
  "Streamline",
  "Thought Space Athletics",
  "Viking Discs",
  "Westside Discs",
] as const;


export type DiscBrand = typeof DiscBrands[number];


// — Plastics —
// This is a curated list of common plastic blends across various brands,
// drawn from plastic-type guides and databases. :contentReference[oaicite:0]{index=0}
export const DiscPlastics = [
  "Baseline",
  "Baseline Hard",
  "Baseline Soft",
  "BioFuzion",
  "Blizzard Champion",
  "BT Hard",
  "BT Medium",
  "BT Soft",
  "Champion",
  "Champion Glow",
  "Champion Glow Gummy",
  "Champion XT Pro",
  "Chalk",
  "Classic",
  "Classic Blend",
  "Classic Soft",
  "Classic SuperSoft",
  "Colored Champion Glow",
  "Cryztal",
  "Cryztal FLX",
  "DX",
  "DX Glow",
  "Echo Star",
  "Eclipse",
  "Electron",
  "Electron Firm",
  "Electron Soft",
  "Elite Z",
  "ESP",
  "ESP FLX",
  "ESP Glo",
  "Fission",
  "Fluid",
  "Frost",
  "Frost Line",
  "Fuzion",
  "GStar",
  "Gateway",
  "Glow",
  "Gold Line",
  "Hybrid",
  "Jawbreaker",
  "JK Pro",
  "K1",
  "K1 Glow",
  "K1 Glow-Line",
  "K1 Grind",
  "K1 Handler",
  "K1 Soft",
  "K2",
  "K3",
  "K3 Glow-Line",
  "K3 Hard",
  "K4",
  "KC Pro",
  "Lucid",
  "Lucid Air",
  "Metal Flake Champion",
  "Moonshine",
  "Neutron",
  "Opto",
  "Opto Air",
  "Origio",
  "Plasma",
  "Premium",
  "Prime",
  "Prime Moonshine",
  "Pro D",
  "Pro Line",
  "Proton",
  "R Pro",
  "R2 Neutron",
  "Recycled",
  "Regrind",
  "Retro",
  "Shimmer",
  "Soft Pro D",
  "Star",
  "StarLite",
  "Super Soft",
  "Super Stupid Soft",
  "Ti",
  "Titanium",
  "Tough Jawbreaker",
  "Tournament",
  "VIP",
  "VIP Air",
  "X",
  "X Soft",
  "XT Pro",
  "Z",
  "Z FLX",
  "Z Glo",
  "Z Lite",
  "Zero",
  "Zero Hard",
  "Zero Medium",
  "Zero Megasoft",
  "Zero Soft",
  // Brand-specific plastics
  "Apex",
  "Amber",
  "Alpha",
  "Atomic",
  "Aura",
  "Bravo Glow",
  "Bronze",
  "C Blend",
  "C Line",
  "Charlie",
  "Cosmic",
  "D Blend",
  "Delta 1",
  "Delta 2",
  "Delta T",
  "Diamond Glow",
  "D Line",
  "D Line Glow",
  "E Class",
  "Elasto",
  "Eraser",
  "Eternal",
  "Ethos",
  "Ethereal",
  "ET",
  "Evolution",
  "Evolution Diamond",
  "Express",
  "Excel",
  "Founders",
  "Fossil",
  "Fossil Fuel",
  "Flex",
  "Frontline",
  "Frontline-X",
  "G Blend",
  "G Line",
  "Glow C Blend",
  "Glow C Line",
  "Gold",
  "Gravity",
  "Ground",
  "High Performance",
  "Hydra",
  "I Blend",
  "Icon",
  "Legend",
  "Lima",
  "Lucid X",
  "Magma",
  "Magma Soft",
  "Main Line",
  "Megasoft",
  "Millenium Standard",
  "Nebula",
  "Organic",
  "P Blend",
  "P Line",
  "Performance",
  "Performance Grip",
  "Pinnacle",
  "Platinum",
  "Platinum Organic",
  "Prehistoric",
  "Priority",
  "Protégé",
  "Pure White",
  "Quantum",
  "Recon",
  "S Blend",
  "S Line",
  "Sirius",
  "SP Line",
  "SP Line D Line",
  "SP Line Glow",
  "Strata",
  "Sublime",
  "Supersoft",
  "Terra",
  "Terra Firma",
  "Top Line",
  "Treeline",
  "Ultralight",
  "Ultrium",
  "Basic",
  "Victor 1",
  "Victor 2",
  "X Blend",
  "X Line",
  "200",
  "300S",
  "350G",
  "350RX",
  "400",
  "400G",
  "400S",
  "400S Light",
  "450",
  "750G",
  "Air",
  "BaseGrip",
  "DuraFlex",
  "Unknown",
] as const;


export type DiscPlastic = typeof DiscPlastics[number];

// — Plastics by Brand —
// Maps each brand to its available plastic types.
// This structure is used for grouped display in picklists.
export const DiscPlasticsByBrand: Record<DiscBrand, DiscPlastic[]> = {
  "ABC": ["Platinum", "Gold", "Bronze"],
  "Above Ground Level": ["Treeline"],
  "Axiom": ["Neutron", "Fission", "R2 Neutron", "Plasma", "Proton", "Eclipse", "Electron", "Electron Firm", "Electron Soft"],
  "Clash Discs": [],
  "Climo Disc Golf": [],
  "Daredevil": ["High Performance", "Flex", "Performance Grip", "Performance"],
  "DGA": ["Pro Line", "SP Line", "SP Line Glow", "SP Line D Line"],
  "Discmania": ["S Line", "G Line", "C Line", "Glow C Line", "X Line", "P Line", "D Line", "D Line Glow"],
  "Discraft": ["Titanium", "ESP", "ESP FLX", "Elite Z", "Z Lite", "Z Glo", "ESP Glo", "Z FLX", "Jawbreaker", "X", "X Soft", "Tough Jawbreaker", "Pro D", "Soft Pro D"],
  "Dynamic Discs": ["Hybrid", "Lucid X", "Fuzion", "BioFuzion", "Lucid", "Lucid Air", "Moonshine", "Fluid", "Classic", "Classic Blend", "Classic Soft", "Classic SuperSoft", "Prime", "Prime Moonshine"],
  "Element Discs": ["Hydra", "Terra Firma", "Terra"],
  "Elevation": [],
  "EV-7": [],
  "Full Turn": ["Express", "Priority", "Ground"],
  "Galaxy Disc Golf": ["E Class"],
  "Gateway": ["Evolution", "Platinum Organic", "Evolution Diamond", "Diamond Glow", "Pure White", "Chalk", "Eraser", "Super Soft", "Super Stupid Soft"],
  "Hyzerbomb": ["Frontline", "Frontline-X", "Recon", "Baseline Hard", "Baseline", "Baseline Soft"],
  "Infinite Discs": ["S Blend", "G Blend", "C Blend", "Glow C Blend", "I Blend", "X Blend", "P Blend", "D Blend"],
  "Innova": ["Shimmer", "Star", "StarLite", "Echo Star", "GStar", "Champion", "Blizzard Champion", "Champion Glow", "Colored Champion Glow", "Champion Glow Gummy", "Champion XT Pro", "KC Pro", "R Pro", "JK Pro", "DX", "DX Glow"],
  "Kastaplast": ["K2", "K1", "K1 Glow", "K3"],
  "Latitude 64": ["Hybrid", "Gold Line", "Recycled", "Opto", "Opto Air", "Moonshine", "Frost Line", "Zero Hard", "Zero Medium", "Zero Soft", "Zero Megasoft", "Retro"],
  "Legacy": ["Icon", "Legend", "Pinnacle", "Ultralight", "Protégé", "Gravity", "Excel"],
  "Lone Star Discs": ["Charlie", "Founders", "Alpha", "Lima", "Bravo Glow", "Delta 2", "Delta 1", "Victor 2", "Victor 1"],
  "Millenium": ["Sirius", "Quantum", "ET", "Millenium Standard", "Delta T", "Supersoft"],
  "Mint Discs": ["Apex", "Sublime", "Eternal"],
  "MVP": ["Neutron", "Fission", "Plasma", "Proton", "Eclipse", "Electron", "Electron Firm", "Electron Soft"],
  "Plastic Addicts": ["Top Line", "Main Line"],
  "Prodigy": ["750G", "400G", "450", "400", "400S", "400S Light", "Air", "DuraFlex", "350G", "BaseGrip", "300S", "350RX", "200"],
  "Prodiscus": ["Ultrium", "Premium", "Basic"],
  "Reptilian Disc Golf": ["Amber", "Fossil", "Fossil Fuel", "Prehistoric", "Organic"],
  "RPM": ["Atomic", "Cosmic", "Magma", "Magma Soft", "Strata"],
  "Streamline": ["Neutron", "Fission", "Plasma", "Proton", "Eclipse", "Electron", "Electron Firm", "Electron Soft"],
  "Thought Space Athletics": ["Nebula", "Aura", "Ethereal", "Ethos"],
  "Viking Discs": [],
  "Westside Discs": ["Hybrid", "Tournament", "Recycled", "VIP", "VIP Air", "Moonshine", "Elasto", "BT Hard", "BT Medium", "BT Soft", "Megasoft", "Origio"],
};

// Helper function to get plastics for a specific brand
export function getPlasticsByBrand(brand: DiscBrand | ''): DiscPlastic[] {
  if (!brand) return [...DiscPlastics];
  return DiscPlasticsByBrand[brand] || [];
}

// Helper function to get all brands that have a specific plastic
export function getBrandsForPlastic(plastic: DiscPlastic): DiscBrand[] {
  return (DiscBrands.filter((brand) => 
    DiscPlasticsByBrand[brand]?.includes(plastic)
  ) as DiscBrand[]);
}